name: Create DAB Repository

on:
  # pull_request:
  #   branches:
  #     - main
  #   types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  create-dab-repo:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: |
          pip install pynacl
          pip install niet
          pip install pyyaml

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sudo bash

      - name: Make Script Executable
        run: chmod +x repo_creation.sh

      - name: Run Script
        env:
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PAT }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_HOST_URL: ${{ secrets.DATABRICKS_HOST }}
        run: |
          bash repo_creation.sh -p config.yml
